diagnosis/urls.py
from django.conf.urls import url

from diagnosis.views import (
    clear_cart,
    scanning,
    request_scanning,
    add_item_to_cart,
    remove_item_from_cart,

    report,
    printing,
    invoice,
    status,
    report_write,
)

urlpatterns = [
    url(r'^$', scanning, name='add'),
    url(r'^print/(?P<key>[0-9]+)/$', printing, name='print'),
    url(r'^invoice/(?P<key>[0-9]+)/$', invoice, name='invoice'),
    url(r'^clear_cart/$', clear_cart, name='clear_cart'),
    url(r'^status/$', status, name='status'),
    url(r'^request/scanning$', request_scanning, name='request_scanning'),
    url(r'^new/cart/(?P<key>[0-9]+)$', add_item_to_cart, name='cart_add'),
    url(r'^new/cart/remove/(?P<key>[0-9]+)/$', remove_item_from_cart, name='cart_remove'),
    url(r'^write/report/(?P<key>[0-9]+)$', report_write, name='report_write'),
    url(r'^report/$', report, name='report'),
]

index/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    login,
    logout,
)

from index.views import (
    login_,
    register,
    profile,
    lockscreen,
    error_page,
    create_admin,
    subscriptions,
    admin_dashboard,
    subscriptions_list
)

urlpatterns = [
    url(r'^login/$', login_, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^lock/$', lockscreen, name='lock_screen'),
    url(r'^register/$', register, name='register'),

    url(r'^profile/$', profile, name='profile'),
    url(r'^error/$', error_page, name='error_page'),

    url(r'^administrator/$', admin_dashboard, name='admin_dashboard'),
    url(r'^subscriptions/list/$', subscriptions_list, name='subscriptions_list'),
    url(r'^administrator/create/$', create_admin, name='create_admin'),
    url(r'^subscription/(?P<key>\d+)/$', subscriptions, name='subscriptions'),
]

major_pro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('temp.urls', namespace='temp')),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^lab/', include('laboratory.urls', namespace='lab')),
    url(r'^diagnosis/', include('diagnosis.urls', namespace='diagnosis')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.conf.urls import url

from staff.views import (
    employee,
    user_account,
    employee_add,
    employee_check,
)

urlpatterns = [
    url(r'^employee/$', employee, name='employee'),
    url(r'^employee/add/$', employee_add, name='employee_add'),
    url(r'^account/user/$', user_account, name='account'),
    url(r'^employee/(?P<key>\d+)/$', employee_check, name='employee_check'),
]

temp/urls.py
from django.conf.urls import url
from temp.views import (
    index
)


urlpatterns = [
    url(r'^dashboard/$', index, name='dashboard'),
]

index/templates/base.html
<!DOCTYPE html>
<html dir="ltr" lang="en" class="no-outlines">
<!-- Mirrored from themelooks.net/demo/dadmin/html/blank.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Aug 2018 10:16:35 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}{% if account %}|LAB Express{% endif %}</title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" href="/static/icons/favicon.png" type="image/png">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700%7CMontserrat:400,500">
    <link rel="stylesheet" href="/static/css/custom.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" href="/static/css/morris.min.css">
    <link rel="stylesheet" href="/static/css/select2.min.css">
    <link rel="stylesheet" href="/static/css/jquery-jvectormap.min.css">
    <link rel="stylesheet" href="/static/css/horizontal-timeline.min.css">
    <link rel="stylesheet" href="/static/css/weather-icons.min.css">
    <link rel="stylesheet" href="/static/css/dropzone.min.css">
    <link rel="stylesheet" href="/static/css/ion.rangeSlider.min.css">
    <link rel="stylesheet" href="/static/css/ion.rangeSlider.skinFlat.min.css">
    <link rel="stylesheet" href="/static/css/datatables.min.css">
    <link rel="stylesheet" href="/static/css/fullcalendar.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    {% block style %}

    {% endblock %}
</head>
<body>
<div class="wrapper">
    {% include 'header.html' %}
    {% include 'sidebar.html' %}

    <main class="main--container">
        <section class="page--header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <h2 class="page--title h5">
                            {% block page_title %}Blank Page{% endblock %}
                        </h2>
                        <ul class="breadcrumb">
                            {% block breadcrumb %}
                                <li class="breadcrumb-item"><a href="">Dashboard</a></li>
                                <li class="breadcrumb-item"><span>Page Layouts</span></li>
                            {% endblock %}
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <div class="summary--widget">
                            <div class="summary--item">
                                <p class="summary--chart"
                                   data-trigger="sparkline"
                                   data-type="bar" data-width="5" data-height="38"
                                   data-color="#009378">
                                    2, {# 9,7,9,10,9  #}
                                </p>
                                <p class="summary--title">Sept Patient</p>
                                <p class="summary--stats text-green">5</p>
                            </div>
                            <div class="summary--item">
                                <p class="summary--chart" data-trigger="sparkline"
                                   data-type="bar" data-width="5" data-height="38"
                                   data-color="#e16123">11,</p>
                                <p class="summary--title">Oct Patient</p>
                                <p class="summary--stats text-orange">7</p></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {% block content %}

        {% endblock %}
        <footer class="main--footer main--footer-light">
            <p>Copyright &copy; <a href="#">Haruna Tijjani</a>. All Rights Reserved. </p>
        </footer>
    </main>
</div>

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/jquery-ui.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/perfect-scrollbar.min.js"></script>
<script src="/static/js/jquery.sparkline.min.js"></script>
<script src="/static/js/raphael.min.js"></script>
<script src="/static/js/morris.min.js"></script>
<script src="/static/js/select2.min.js"></script>
<script src="/static/js/jquery-jvectormap.min.js"></script>
<script src="/static/js/jquery-jvectormap-world-mill.min.js"></script>
<script src="/static/js/horizontal-timeline.min.js"></script>
<script src="/static/js/jquery.validate.min.js"></script>
<script src="/static/js/jquery.steps.min.js"></script>
<script src="/static/js/dropzone.min.js"></script>
<script src="/static/js/ion.rangeSlider.min.js"></script>
<script src="/static/js/datatables.min.js"></script>
<script src="/static/js/main.js"></script>
{% block javascripts %}{% endblock %}
</body>
<!-- Mirrored from themelooks.net/demo/dadmin/html/blank.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Aug 2018 10:16:35 GMT -->
</html>

index/templates/error.html
<!DOCTYPE html>
<html dir="ltr" lang="en" class="no-outlines">
<!-- Mirrored from themelooks.net/demo/dadmin/html/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Aug 2018 10:17:17 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" href="favicon.png" type="image/png">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700%7CMontserrat:400,500">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/css/perfect-scrollbar.min.css">
    <link rel="stylesheet" href="/static/css/morris.min.css">
    <link rel="stylesheet" href="/static/css/select2.min.css">
    <link rel="stylesheet" href="/static/css/jquery-jvectormap.min.css">
    <link rel="stylesheet" href="/static/css/horizontal-timeline.min.css">
    <link rel="stylesheet" href="/static/css/weather-icons.min.css">
    <link rel="stylesheet" href="/static/css/dropzone.min.css">
    <link rel="stylesheet" href="/static/css/ion.rangeSlider.min.css">
    <link rel="stylesheet" href="/static/css/ion.rangeSlider.skinFlat.min.css">
    <link rel="stylesheet" href="/static/css/datatables.min.css">
    <link rel="stylesheet" href="/static/css/fullcalendar.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="wrapper">
    <div class="m-error m-error-404">
        <div class="m-error--content">
            <div class="m-error--title"><h1 class="h1">{{ title_head }}</h1></div>
            <div class="m-error--desc"><h2 class="h2">{{ title }}</h2>
                <p>{{ content }}</p>
                <a href="{% url 'temp:dashboard' %}" class="btn btn-block btn-rounded btn-info">Go Back To
                    Dashboard</a>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/jquery-ui.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/perfect-scrollbar.min.js"></script>
<script src="/static/js/jquery.sparkline.min.js"></script>
<script src="/static/js/raphael.min.js"></script>
<script src="/static/js/morris.min.js"></script>
<script src="/static/js/select2.min.js"></script>
<script src="/static/js/jquery-jvectormap.min.js"></script>
<script src="/static/js/jquery-jvectormap-world-mill.min.js"></script>
<script src="/static/js/horizontal-timeline.min.js"></script>
<script src="/static/js/jquery.validate.min.js"></script>
<script src="/static/js/jquery.steps.min.js"></script>
<script src="/static/js/dropzone.min.js"></script>
<script src="/static/js/ion.rangeSlider.min.js"></script>
<script src="/static/js/datatables.min.js"></script>
<script src="/static/js/main.js"></script>
</body>
<!-- Mirrored from themelooks.net/demo/dadmin/html/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Aug 2018 10:17:17 GMT -->
</html>

index/templates/header.html
<header class="navbar navbar-fixed">
    <div class="navbar--header">
        <a href="" class="logo">
            {% comment %}
                <img src="/static/img/account/wrapper-bg.jpg" alt="">
            {% endcomment %}
            <h3><b style="color: #20c997">LAB | </b>{% if account %}{{ account.employee.institution }}{% else %} Epress{% endif %}</h3>
        </a>
        <a href="#" class="navbar--btn" data-toggle="sidebar" title="Toggle Sidebar"> <i class="fa fa-bars"></i>
        </a>
    </div>
    <a href="#" class="navbar--btn" data-toggle="sidebar" title="Toggle Sidebar"> <i class="fa fa-bars"></i> </a>
    {% comment %}
    <div class="navbar--search">
        <form action=""><input type="search" name="search"
                               class="form-control"
                               placeholder="Search Something..."
                               required>
            <button class="btn-link"><i class="fa fa-search"></i></button>
        </form>
    </div>
    {% endcomment %}
    <div class="navbar--nav ml-auto">
        <ul class="nav">
            <li class="nav-item"><a href="#" class="nav-link"> <i class="fa fa-bell"></i> <span
                    class="badge text-white bg-blue">7</span> </a></li>
            <li class="nav-item"><a href="" class="nav-link"> <i class="fa fa-envelope"></i> <span
                    class="badge text-white bg-blue">4</span> </a></li>
            <li class="nav-item dropdown nav--user online"><a href="#" class="nav-link" data-toggle="dropdown">
                <img src="/static/img/avatars/haroun.jpg" alt="" class="rounded-circle"> <span>Haruna Tijjani</span>
                <i class="fa fa-angle-down"></i> </a>
                <ul class="dropdown-menu">
                    <li><a href="profile.html"><i class="far fa-user"></i>Profile</a></li>
                    <li><a href=""><i class="far fa-envelope"></i>Inbox</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a href=""><i class="fa fa-lock"></i>Lock Screen</a></li>
                    <li><a href="{% url 'index:logout' %}"><i class="fa fa-power-off"></i>Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
</header>

index/templates/sidebar.html
<aside class="sidebar" data-trigger="scrollbar">
    <div class="sidebar--profile">
        <div class="profile--img">
            <a href="profile.html">
                <img src="/static/img/avatars/haroun.jpg" alt="" class="rounded-circle">
            </a>
        </div>
        <div class="profile--name"><a href="" class="btn-link">Haruna Tijjani Zango</a></div>
        <div class="profile--nav">
            <ul class="nav">
                <li class="nav-item"><a href="{% url 'index:profile' %}" class="nav-link" title="User Profile"> <i
                        class="fa fa-user"></i> </a></li>
                {% if account %}
                    <li class="nav-item"><a href="{% url 'index:lock_screen' %}" class="nav-link" title="Lock Screen"> <i
                            class="fa fa-lock"></i> </a></li>
                {% endif %}
                <li class="nav-item"><a href="" class="nav-link" title="Messages"> <i
                        class="fa fa-envelope"></i> </a></li>
                <li class="nav-item"><a href="{% url 'index:logout' %}" class="nav-link" title="Logout">
                    <i class="fa fa-sign-out-alt"></i>
                </a></li>
            </ul>
        </div>
    </div>
    {% if account %}
        <div class="sidebar--nav">
            <ul>
                <li><a href="#">Laboratory Department</a>
                    <ul>
                        {% comment %}
                    {% with path='url-path' title='Tita' icon='fa-table' %}
                        {% include 'components/nav_link.html' %}
                    {% endwith %}
                    {% endcomment %}
                        {% if account.category != 'Consultant' %}
                            <li class="active open"><a href="#"> <i class="fa fa-th"></i> <span>Test</span> </a></li>
                            <li><a href="#"> <i class="fa fa-th-list"></i> <span>Make Request</span> </a></li>
                        {% endif %}
                        {% if account.category != 'Receptionist' %}
                            <li><a href="#"> <i class="far fa-envelope"></i> <span>Compute Report</span> </a></li>
                        {% endif %}
                        {% if account.category != 'Consultant' %}
                            <li><a href=""> <i class="far fa-calendar-alt"></i> <span>Status</span> </a></li>
                        {% endif %}
                    </ul>
                </li>
                <li><a href="#">Diagnostic Department</a>
                    <ul>
                        {% if account.category != 'Consultant' %}
                            <li><a href="{% url 'diagnosis:add' %}"> <i class="far fa-newspaper"></i>
                                <span>Diagnostic Scan</span> </a></li>
                            <li><a href="{% url 'diagnosis:request_scanning' %}"> <i class="fab fa-wpforms"></i> <span>Make Request</span>
                            </a></li>
                        {% endif %}
                        {% if account.category != 'Receptionist' %}
                            <li><a href="{% url 'diagnosis:report' %}"> <i class="far fa-comments"></i>
                                <span>Write Report</span>
                            </a></li>
                        {% endif %}
                        {% if account.category != 'Consultant' %}
                            <li><a href="{% url 'diagnosis:status' %}"> <i class="far fa-address-book"></i>
                                <span>Status</span>
                            </a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if account.category == 'Admin' %}
                    <li><a href="#">Administrator</a>
                        <ul>
                            <li><a href=""> <i class="far fa-sticky-note"></i> <span>Manage News</span> </a></li>
                            <li><a href=""> <i class="fa fa-tasks"></i> <span>General Sales</span> </a></li>
                            <li><a href="{% url 'staff:account' %}"> <i class="fa fa-search"></i>
                                <span>Manage Users</span>
                            </a>
                            </li>
                            <li><a href="{% url 'staff:employee' %}"> <i class="fab fa-wpforms"></i>
                                <span>Manage Employees</span> </a></li>
                            <li><a href=""> <i class="far fa-comments"></i> <span>General Report</span> </a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% else %}
        <div class="sidebar--nav">
            <ul>
                <li><a href="#">Administrator Panel</a>
                    <ul>
                        {% comment %}
                    {% with path='url-path' title='Tita' icon='fa-table' %}
                        {% include 'components/nav_link.html' %}
                    {% endwith %}
                    {% endcomment %}
                        <li class="active open"><a href="{% url 'index:admin_dashboard' %}">
                            <i class="fa fa-th"></i> <span>Institutions</span> </a>
                        </li>
                        <li><a href="{% url 'index:subscriptions_list' %}">
                            <i class="fa fa-th-list"></i> <span>Subscriptions</span> </a>
                        </li>
                        <li><a href="{% url 'index:create_admin' %}"> <i class="far fa-envelope"></i>
                            <span>Admin-User</span> </a></li>
                        <li><a href="{% url 'index:profile' %}"> <i class="far fa-calendar-alt"></i> <span>Profile</span> </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    {% endif %}
</aside>