major_pro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('temp.urls', namespace='temp')),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^', include('staff.urls', namespace='staff')),
    url(r'^lab/', include('laboratory.urls', namespace='lab')),
    url(r'^diagnosis/', include('diagnosis.urls', namespace='diagnosis')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.conf.urls import url

from staff.views import (
    employee,
    user_account,
    employee_add,
    employee_check,
)

urlpatterns = [
    url(r'^employee/$', employee, name='employee'),
    url(r'^employee/add/$', employee_add, name='employee_add'),
    url(r'^account/user/$', user_account, name='account'),
    url(r'^employee/(?P<key>\d+)/$', employee_check, name='employee_check'),
]

temp/urls.py
from django.conf.urls import url
from temp.views import (
    index
)


urlpatterns = [
    url(r'^dashboard/$', index, name='dashboard'),
]

staff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

from index.models import Institution

STAFF_CATEGORY = (
    ('Admin', 'Admin'),
    ('Receptionist', 'Receptionist'),
    ('Consultant', 'Consultant'))
STATUE = (('Married', 'Married'), ('Single', 'Single'))
SEX = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))


# Create your models here.
class Employee(models.Model):
    institution = models.ForeignKey(Institution, related_name='cooperation')
    name = models.CharField(max_length=100)
    passport = models.ImageField(blank=True, upload_to='passport')
    sex = models.CharField(max_length=20, choices=SEX)
    status = models.CharField(max_length=20, choices=STATUE)
    date_of_birth = models.DateField(max_length=10)
    nationality = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.IntegerField()
    date_employed = models.DateField()
    visible = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.name)


class Account(models.Model):
    user = models.ForeignKey(User, related_name='users')
    employee = models.OneToOneField(Employee, related_name='agent')
    category = models.CharField(max_length=100, choices=STAFF_CATEGORY)
    lock = models.BooleanField(default=False)

    def __str__(self):
        return "{}  {}".format(self.employee.institution, self.user)

staff/forms.py
from django import forms
from staff.models import (
    Employee,
    Account,
)


class AddEmployeeFrom(forms.ModelForm):

    class Meta:
        model = Employee
        fields = (
            'name',
            'sex',
            'status',
            'date_of_birth',
            'date_employed',
            'passport',
            'nationality',
            'address',
            'phone',
        )


class CreateUserAccountForm(forms.ModelForm):
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}), label='Password:')
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}), label='Username:')

    class Meta:
        model = Account
        fields = (
            'employee',
            'username',
            'category',
            'password',
        )

    def __init__(self, account, *args, **kwargs):
        super(CreateUserAccountForm, self).__init__(*args, **kwargs)
        self.fields['employee'].queryset = Employee.objects.filter(institution=account.employee.institution)

staff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import (
    render,
    redirect,
    HttpResponseRedirect,
)

from staff.forms import (
    AddEmployeeFrom,
    CreateUserAccountForm,
)
from staff.models import (
    Account,
    Employee,
)


# Create your views here.
@login_required
def employee(request):
    instance = Account.objects.get(user=request.user)
    context = {
        'employees': Employee.objects.filter(institution=instance.employee.institution),
    }
    return render(request, 'employee.html', context)


def employee_check(request, key):
    context = {
        'employee_check': Employee.objects.get(id=key),
        'employees': Employee.objects.all(),
    }
    return render(request, 'employee.html', context)


@login_required
def employee_add(request):
    form = AddEmployeeFrom(request.POST or None)
    print ('trying')
    if form.is_valid():
        print ('pass')
        instance = form.save(commit=False)
        account = Account.objects.get(user=request.user)
        instance.institution = account.employee.institution
        instance.save()
        return redirect("/employee")

    print ('Failed')
    context = {
        'form': AddEmployeeFrom,
        'error': form.errors
    }
    return render(request, 'employee_add.html', context)


@login_required
def user_account(request):
    account_instance = Account.objects.get(user=request.user)
    if request.method == 'POST':
        form_post = CreateUserAccountForm(account_instance, request.POST)
        if form_post.is_valid():
            user = User()
            account = form_post.save(commit=False)
            username = form_post.cleaned_data['username']
            password = form_post.cleaned_data['password']
            if username:
                user_name = User.objects.filter(username=username)
                if user_name:
                    messages.error(request, "Username already exist")
                    return redirect('/account/user/')
            if len(password) <= 4:
                messages.error(request, "Passwords must contain at least 5 characters")
                return redirect('/account/user/')

            user.username = username
            user.set_password(password)
            user.save()

            account_instance = Account.objects.get(user=request.user)
            account.institution = account_instance.employee.institution
            account.user = user
            account.save()
            messages.success(request, "Employee account created")
            return redirect("/account/user/")
        else:
            context = {
                'form': form_post,
                'accounts': Account.objects.filter(employee__institution=account_instance.employee.institution),
                'error': form_post.errors
            }
            return render(request, 'users.html', context)
    form = CreateUserAccountForm(account_instance)
    context = {
        'form': form,
        'accounts': Account.objects.filter(employee__institution=account_instance.employee.institution),
    }
    return render(request, 'users.html', context)

staff/templates/employee.html
{% extends 'base.html' %}

{% block content %}
<section class="main--content">
    <div class="row gutter-20">
        <div class="col-md-{% if employee_check %}8{% else %}12{% endif %}">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title pad">Employee(s)</h3>
                    <a href="{% url 'staff:employee_add' %}" class="btn btn-sm btn-outline-info ">Add Employee</a>
                </div>
                <div class="panel-content">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Sex</th>
                            {% if not employee_check %}
                                <th>Status</th>
                                <th>Phone No</th>
                                <th>Nationality</th>
                            {% endif %}
                            <th>Check</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for employee in employees %}
                            <tr class="gradeX">
                                <td>{{ employee.name }}</td>
                                <td>{{ employee.sex }}</td>
                                {% if not employee_check %}
                                    <td>{{ employee.status }}</td>
                                    <td>{{ employee.phone }}</td>
                                    <td>{{ employee.nationality }}</td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'staff:employee_check' employee.id %}">
                                        <button class="btn btn-dark">Check</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% if employee_check %}
            <div class="col-md-4">
            <div class="panel">
            <div class="panel-heading"><h3 class="panel-title">About Me</h3></div>
            <div class="panel-content panel-about">
        {% if employee_check.passport %}
            <img class="" src="{{ employee_check.passport.url }}" id="image_preview" alt="Avatar">
        {% else %}
            <img class="rounded-circle" src="/static/img/avatars/haroun.jpg" id="image_preview" alt="Avatar">
        {% endif %}
        <p><b>Address: </b>{{ employee_check.address }}</p>
        <p><b>Nationality: </b>{{ employee_check.nationality }}</p>
        <p><b>Joined On: </b>{{ employee_check.date_employed }}</p>
        <table>
            <tr>
                <th><i class="fas fa-briefcase"></i>Permission</th>
                <td>{% if employee_check.agent %}None{% else %}{{ employee_check.agent }}{% endif %}</td>
            </tr>
            <tr>
                <th><i class="fas fa-birthday-cake"></i>Date of Birth</th>
                <td>{{ employee_check.date_of_birth }}</td>
            </tr>
            <tr>
                <th><i class="fas fa-map-marker-alt"></i>Sex</th>
                <td>{{ employee_check.sex }}</td>
            </tr>
            <tr>
                <th><i class="fas fa-mobile-alt"></i>Mobile No.</th>
                <td><a href="tel:{{ employee_check.phone }}"
                       class="btn-link">{{ employee_check.phone }}</a></td>
            </tr>
            <tr>
                <th><i class="fas fa-globe"></i>Status</th>
                <td><a href="mailto:example.com" class="btn-link">{{ employee_check.status }}</a></td>
            </tr>
        </table>
        </div>
        </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block javascripts %}
    <script src="/static/datatables/jquery.dataTables.js"></script>
    <script src="/static/datatables/dataTables.bootstrap4.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/static/datatables/sb-admin-datatables.min.js"></script>
{% endblock %}

staff/templates/employee_add.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
    <link rel="stylesheet" href="/static/css/sweetalert.min.css">
    <link rel="stylesheet" href="/static/css/sweetalert-overrides.css">
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading"><h3 class="panel-title">Form Elements</h3></div>
            <div class="panel-content">{{ error }}
                <form method="post">{% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Name</span>
                                <div class="col-md-8">
                                    {% render_field form.name placeholder="Name..." class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Passport</span>
                                <div class="col-md-8">
                                    <label class="custom-file">
                                        {% render_field form.passport class="custom-file-input" %}
                                        <span class="custom-file-label">Passport</span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Address</span>
                                <div class="col-md-8">
                                    {% render_field form.address placeholder="Address..." class="form-control" %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Sex</span>
                                <div class="col-md-8">
                                    {% render_field form.sex class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Status</span>
                                <div class="col-md-8">
                                    {% render_field form.status class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Employed No</span>
                                <div class="col-md-8">
                                    {% render_field form.date_employed placeholder='MM-DD-YYYY' class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Dob</span>
                                <div class="col-md-8">
                                    {% render_field form.date_of_birth placeholder='MM-DD-YYYY' class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Nationality</span>
                                <div class="col-md-8">
                                    {% render_field form.nationality placeholder="Nationality..." class="form-control" %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <span class="label-text col-md-4 col-form-label text-md-right">Phone</span>
                                <div class="col-md-8">
                                    {% render_field form.phone placeholder="Phone..." class="form-control" %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-block btn-success" > Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    <script src="/static/js/sweetalert.min.js"></script>
    <script src="/static/js/sweetalert-init.js"></script>
{% endblock %}

staff/templates/users.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Add Scan{% endblock %}

{% block page_title %}Users {% endblock %}

{% block content %}

    <section class="main--content">
        <div class="row gutter-20">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title pad">User(s)</h3>
                        <a href="#add-user" class="btn btn-sm btn-outline-info" data-toggle="modal">
                            Create New User Account
                        </a>
                    </div>
                    <div class="panel-content">
                        <table class="table table-bordered" id="dataTable" width="200%" cellspacing="0">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close"
                                                    data-dismiss="alert"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            <i class="fa fa-times-circle"></i> {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}

                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="close"
                                                data-dismiss="alert"
                                                aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <i class="fa fa-times-circle"></i> {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{% if message.tags == 'success' %}dark{% else %}danger{% endif %} alert-dismissible"
                                         role="alert">
                                        <button type="button" class="close" data-dismiss="alert"
                                                aria-label="Close"><span
                                                aria-hidden="true">&times;</span></button>
                                        <i class="fa fa-times-circle"></i> {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Username</th>
                                <th>Hierarchy</th>
                                <th>last Login</th>
                                <th>Deactivate</th>
                                <th>Check</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for user in accounts %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ user.user.username }}</td>
                                    <td>{{ user.category }}</td>
                                    <td>{{ user.user.last_login }}</td>
                                    <td>Deactivate</td>
                                    <td><a href="">
                                        <button class="btn btn-dark">Check</button>
                                    </a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div id="add-user" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"><h5 class="modal-title">Create Account</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="modal-body">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-user-circle"></i> </span>
                            </div>
                            {% render_field form.employee class="form-control" %}
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i> </span>
                            </div>
                            {% render_field form.username name="email" class="form-control" placeholder='Username ...' %}
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-baseball-ball"></i> </span>
                            </div>
                            {% render_field form.category class="form-control" %}
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-star"></i> </span>
                            </div>
                            {% render_field form.password name="email" class="form-control" placeholder='Password' %}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Create User</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/static/datatables/jquery.dataTables.js"></script>
    <script src="/static/datatables/dataTables.bootstrap4.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/static/datatables/sb-admin-datatables.min.js"></script>
{% endblock %}